definitions:
  command.CreateMeasureType:
    properties:
      name:
        maxLength: 10
        type: string
    required:
    - name
    type: object
  command.UpdateMeasureType:
    properties:
      id:
        maxLength: 24
        minLength: 24
        type: string
      name:
        maxLength: 10
        type: string
    required:
    - id
    - name
    type: object
  response.MeasureTypeResponse:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
  responses.ErrorResponse:
    properties:
      errorId:
        type: string
      errors:
        additionalProperties:
          type: string
        type: object
      message:
        type: string
      status:
        type: integer
      title:
        type: string
    type: object
  responses.PaginatedResponse:
    properties:
      data: {}
      pageSize:
        type: integer
      start:
        type: integer
      total:
        type: integer
    type: object
info:
  contact:
    email: juan.abanto@sofisoft.pe
    name: Sofisoft Technologies SAC
    url: https://sofisoft.pe
  description: Specifying services for measure units.
  license:
    name: MIT License
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: MeasureUnit API
  version: v1
paths:
  /api/v1/measuretypes:
    get:
      consumes:
      - application/json
      parameters:
      - description: word to search
        in: query
        name: name
        type: string
      - description: Number of results per page
        in: query
        name: pageSize
        type: integer
      - description: Page number
        in: query
        name: start
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.PaginatedResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
      summary: Return a Measure Type List.
      tags:
      - MeasureTypes
    patch:
      consumes:
      - application/json
      parameters:
      - description: Object to be modified.
        in: body
        name: command
        required: true
        schema:
          $ref: '#/definitions/command.UpdateMeasureType'
      produces:
      - application/json
      responses:
        "204":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
      summary: Update a type of measure.
      tags:
      - MeasureTypes
    post:
      consumes:
      - application/json
      parameters:
      - description: Object to be created.
        in: body
        name: command
        required: true
        schema:
          $ref: '#/definitions/command.CreateMeasureType'
      produces:
      - application/json
      responses:
        "201":
          description: Id of the created object
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
      summary: Create a new type of measure.
      tags:
      - MeasureTypes
  /api/v1/measuretypes/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: MeasureType Id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
      summary: Delete a measure type by Id.
      tags:
      - MeasureTypes
    get:
      consumes:
      - application/json
      parameters:
      - description: MeasureType Id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.MeasureTypeResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
      summary: Get a measure type by Id.
      tags:
      - MeasureTypes
swagger: "2.0"
